### PR TITLE
feat(scripts/fetch_binary.d): Fetching dmd source and misc improvement.

### PR DESCRIPTION
**Pull request by dukc**
Along with ability to fetch dmd sources, the largest improvement is a better help page.

ping @PetarKirov

### CODE REVIEW

**Comment by dukc** [comment]
I just used this to actually fetch some DMD sources. It turns out the hashing needs to be done differently, since dmd sources are NAR hashed in unpacked form as opposed to content hash of the `.tar.gz` as in other downloads. I've adapted the hashing command and it now works. Unfortunately this means using vanilla Nix commands as the new-gen equivalents either don't have the necessary flags for this scenario or are documented really badly.

ping @PetarKirov .

**Comment by dukc** [comment]
Ping @PetarKirov

Any issues with this? I'm going to merge at 15th or later if no answer, as the CI is passing.

**Comment by PetarKirov** [comment]
@dukc Sorry for delay! In addition to the lack of available time on my side, I had started a large refactoring that of this script and I was hoping I could finish it before merging your code to avoid conflicts, but I think at this point it would be better if I merge your PR and redo my stuff, to avoid any additional delays.

**Review by PetarKirov — APPROVED** [review]

**Comment by dukc** [comment]
Thanks!

**Pull request merged**
