### PR TITLE
refactor(pkgs): Remove obsolete code and streamline the implementation'

### PR DESCRIPTION
**Pull request by PetarKirov**
- config(git): Ignore ci-matrix artifacts
- refactor(pkgs/*/): Delete obsolete files

### CODE REVIEW

**Review by dukc — COMMENTED** [review]
Good refactoring, although it unfortunately will have some merge conflicts with my LDC bootstrap PR. Apart from the question of merge conflicts, LGTM.

**Comment by dukc** [comment]
ping @PetarKirov what's the status on this?

**Comment by PetarKirov** [comment]
> ping @PetarKirov what's the status on this?

@dukc 

It turns out that using a newer version of LDC to compile older versions of DMD is way harder than I imagined. There were some things that are expected, like older DMD versions using deprecated features (classes + alias this, warnings for unreachable code or delegates returning static arrays in `extern (C++):` blocks), which I was able to fix by:
* [Omitting `-w` and `-de` flags](https://github.com/PetarKirov/dlang.nix/pull/53/commits/daebdde6059ba144c9f16ae3eb5f91b0dc3bbb8f) when compiling dmd packages older than 2.103.0.
* Including a patch from [this PR](https://github.com/dlang/dmd/pull/14127) when building dmd versions older than 2.101.0.

With these changes, I was able to [successfully build](https://github.com/PetarKirov/dlang.nix/actions/runs/8951927182) with LDC 1.34.0 binary the following versions:
* `dmd-2_100_2`
* `dmd-2_102_2`
* `dmd-2_103_1`
* `dmd-2_104_2`
* `dmd-2_105_2`

However `dmd-2_092_1`, `dmd-2_096_1`, `dmd-2_098_1` fail to build with some extremely cryptic errors... dmd does compile, however druntime fails to build with errors like 

> src/core/time.d(1882): Error: incompatible types for array comparison: `string` and `string`

[CI link](https://github.com/PetarKirov/dlang.nix/actions/runs/8953130479/job/24591312434).

In the end, I got tired of making LDC 1.34.0 work as bootstrap compiler and reverter to 1.25.0, which is what your PR used.

**Comment by PetarKirov** [comment]
I'm going ahead with merging this PR as I'd also like to take care of #66 and #55.
That said, I'd appreciate if you have time to review this PR after that - I'll try to address your comments in a future PR.

**Pull request merged**
